import type { Level, Word } from "./types"

let n = 0
function w(
  word: string,
  ipa: string,
  pos: string,
  meaning: string,
  example: string,
  exampleZh: string,
  level: Level,
): Word {
  n += 1
  return {
    id: `seed-${String(n).padStart(3, "0")}`,
    word,
    ipa,
    pos,
    meaning,
    example,
    exampleZh,
    level,
  }
}

export const SEED_WORDS: Word[] = [
  // ───────────────────────── A1 ─────────────────────────
  w("apple", "/ˈæpl/", "n.", "苹果", "I eat an apple every morning.", "我每天早上吃一个苹果。", "A1"),
  w("water", "/ˈwɔːtər/", "n.", "水；水分", "Please give me a glass of water.", "请给我一杯水。", "A1"),
  w("house", "/haʊs/", "n.", "房子；住宅", "They live in a small house near the park.", "他们住在公园附近的一栋小房子里。", "A1"),
  w("book", "/bʊk/", "n.", "书；书籍", "She is reading an interesting book.", "她正在读一本有趣的书。", "A1"),
  w("friend", "/frend/", "n.", "朋友", "He is my best friend since childhood.", "他是我从小的最好的朋友。", "A1"),
  w("happy", "/ˈhæpi/", "adj.", "高兴的；幸福的", "I am happy to see you again.", "再次见到你，我很高兴。", "A1"),
  w("food", "/fuːd/", "n.", "食物", "The food here is very tasty.", "这里的食物非常美味。", "A1"),
  w("morning", "/ˈmɔːrnɪŋ/", "n.", "早晨；上午", "Good morning, everyone.", "大家早上好。", "A1"),
  w("school", "/skuːl/", "n.", "学校", "The children go to school by bus.", "孩子们乘公交车去上学。", "A1"),
  w("family", "/ˈfæməli/", "n.", "家庭；家人", "I love my family very much.", "我非常爱我的家人。", "A1"),
  w("money", "/ˈmʌni/", "n.", "钱；金钱", "He saves money every month.", "他每个月都会存钱。", "A1"),
  w("time", "/taɪm/", "n.", "时间；时刻", "What time is it now?", "现在几点了？", "A1"),
  w("work", "/wɜːrk/", "n./v.", "工作；劳动", "She works in a hospital.", "她在一家医院工作。", "A1"),
  w("name", "/neɪm/", "n.", "名字；名称", "May I have your name, please?", "请问你叫什么名字？", "A1"),
  w("city", "/ˈsɪti/", "n.", "城市", "Beijing is a very big city.", "北京是一座非常大的城市。", "A1"),
  w("love", "/lʌv/", "v./n.", "爱；热爱", "I love learning English.", "我热爱学习英语。", "A1"),
  w("sleep", "/sliːp/", "v.", "睡觉", "I sleep eight hours every day.", "我每天睡八个小时。", "A1"),
  w("breakfast", "/ˈbrekfəst/", "n.", "早餐", "Breakfast is the most important meal.", "早餐是最重要的一餐。", "A1"),
  w("rain", "/reɪn/", "n./v.", "雨；下雨", "It often rains in spring.", "春天经常下雨。", "A1"),
  w("road", "/roʊd/", "n.", "道路；公路", "The road to the village is narrow.", "通往村庄的道路很窄。", "A1"),

  // ───────────────────────── A2 ─────────────────────────
  w("travel", "/ˈtrævəl/", "v.", "旅行", "We traveled to Japan last summer.", "去年夏天我们去了日本旅行。", "A2"),
  w("decide", "/dɪˈsaɪd/", "v.", "决定", "I can't decide what to eat for dinner.", "我没法决定晚餐吃什么。", "A2"),
  w("improve", "/ɪmˈpruːv/", "v.", "改进；提高", "Reading helps improve your vocabulary.", "阅读有助于提高你的词汇量。", "A2"),
  w("because", "/bɪˈkɔːz/", "conj.", "因为", "I was late because the bus was slow.", "我迟到了，因为公交车开得很慢。", "A2"),
  w("different", "/ˈdɪfrənt/", "adj.", "不同的", "We have different opinions about the plan.", "我们对这个计划有不同的看法。", "A2"),
  w("interesting", "/ˈɪntrəstɪŋ/", "adj.", "有趣的", "This is an interesting story.", "这是一个有趣的故事。", "A2"),
  w("remember", "/rɪˈmembər/", "v.", "记得；记住", "Remember to lock the door before you leave.", "离开前记得锁门。", "A2"),
  w("weather", "/ˈweðər/", "n.", "天气", "The weather is really nice today.", "今天天气非常好。", "A2"),
  w("health", "/helθ/", "n.", "健康", "Eating well is good for your health.", "吃得健康有益健康。", "A2"),
  w("experience", "/ɪkˈspɪriəns/", "n.", "经验；经历", "She has five years of teaching experience.", "她有五年的教学经验。", "A2"),
  w("important", "/ɪmˈpɔːrtnt/", "adj.", "重要的", "Sleep is important for children.", "睡眠对孩子很重要。", "A2"),
  w("believe", "/bɪˈliːv/", "v.", "相信；认为", "I believe in myself.", "我相信我自己。", "A2"),
  w("borrow", "/ˈbɔːroʊ/", "v.", "借（入）", "Can I borrow your pen for a minute?", "我能借你的笔用一下吗？", "A2"),
  w("choose", "/tʃuːz/", "v.", "选择", "You can choose any color you like.", "你可以选择你喜欢的任何颜色。", "A2"),
  w("difficult", "/ˈdɪfɪkəlt/", "adj.", "困难的", "The exam was more difficult than I expected.", "考试比我预想的更难。", "A2"),
  w("environment", "/ɪnˈvaɪrənmənt/", "n.", "环境", "We should protect the environment.", "我们应该保护环境。", "A2"),
  w("knowledge", "/ˈnɑːlɪdʒ/", "n.", "知识", "Knowledge is power.", "知识就是力量。", "A2"),
  w("market", "/ˈmɑrkɪt/", "n.", "市场；集市", "She buys vegetables at the market.", "她在市场上买蔬菜。", "A2"),
  w("mistake", "/mɪˈsteɪk/", "n.", "错误", "Everyone makes mistakes, and that's okay.", "每个人都会犯错，这没关系。", "A2"),
  w("neighbor", "/ˈneɪbər/", "n.", "邻居", "Our neighbors are very friendly.", "我们的邻居非常友好。", "A2"),

  // ───────────────────────── B1 ─────────────────────────
  w("achieve", "/əˈtʃiːv/", "v.", "实现；达成", "She worked hard to achieve her goals.", "她努力工作以实现自己的目标。", "B1"),
  w("afford", "/əˈfɔːrd/", "v.", "负担得起", "We can't afford a new car right now.", "我们现在买不起新车。", "B1"),
  w("argue", "/ˈɑːrɡjuː/", "v.", "争论", "They argued about the movie for an hour.", "他们为那部电影争论了一个小时。", "B1"),
  w("benefit", "/ˈbenɪfɪt/", "n.", "好处；利益", "There are many benefits of regular exercise.", "经常锻炼有很多好处。", "B1"),
  w("communicate", "/kəˈmjunɪkeɪt/", "v.", "交流；沟通", "Good communication is the key to a great team.", "良好的沟通是优秀团队的关键。", "B1"),
  w("curious", "/ˈkjʊriəs/", "adj.", "好奇的", "Children are naturally curious about the world.", "孩子对世界天生充满好奇。", "B1"),
  w("develop", "/dɪˈveləp/", "v.", "发展；培养", "This app helps you develop good habits.", "这款应用帮助你培养好习惯。", "B1"),
  w("encourage", "/ɪnˈkɜːrɪdʒ/", "v.", "鼓励", "My teacher always encourages me to speak English.", "我的老师总是鼓励我说英语。", "B1"),
  w("escape", "/ɪˈskeɪp/", "v.", "逃跑；逃脱", "The animals tried to escape from the cage.", "动物们试图从笼子里逃出去。", "B1"),
  w("familiar", "/fəˈmær/", "adj.", "熟悉的", "This song is familiar to everyone.", "这首歌人人都熟悉。", "B1"),
  w("habit", "/ˈhæbɪt/", "n.", "习惯", "Reading before bed is a good habit.", "睡前阅读是个好习惯。", "B1"),
  w("influence", "/ˈɪnfluəns/", "n./v.", "影响", "Music has a great influence on our mood.", "音乐对我们的情绪有很大影响。", "B1"),
  w("journey", "/ˈdʒɜːrni/", "n.", "旅程；行程", "Life is a journey, not a race.", "人生是一段旅程，而不是一场赛跑。", "B1"),
  w("lazy", "/ˈleɪzi/", "adj.", "懒惰的", "Don't be lazy. Start studying now.", "别懒惰，现在就开始学习。", "B1"),
  w("manage", "/ˈmænɪdʒ/", "v.", "管理；设法做到", "He manages a team of ten people.", "他管理着一个十人团队。", "B1"),
  w("opinion", "/oʊˈpɪnjən/", "n.", "意见；看法", "In my opinion, the plan will work.", "在我看来，这个计划是可行的。", "B1"),
  w("patience", "/ˈpeɪʃns/", "n.", "耐心", "Learning a language takes a lot of patience.", "学习一门语言需要很多耐心。", "B1"),
  w("practice", "/ˈpræktɪs/", "n./v.", "练习；实践", "Daily practice is the best way to improve.", "每天练习是提高的最好方法。", "B1"),
  w("refuse", "/rɪˈfjuz/", "v.", "拒绝", "She refused to answer the question.", "她拒绝回答那个问题。", "B1"),
  w("suggest", "/səˈdʒest/", "v.", "建议", "I suggest we leave early to avoid the traffic.", "我建议我们早点出发以避开交通拥堵。", "B1"),

  // ───────────────────────── B2 ─────────────────────────
  w("accomplish", "/əˈkmplɪ/", "v.", "完成；实现", "He accomplished everything on his to-do list.", "他完成了待办清单上的一切。", "B2"),
  w("analyze", "/ˈænəlaɪz/", "v.", "分析", "Let's analyze the data before making a decision.", "在做决定之前，我们先分析一下数据。", "B2"),
  w("aware", "/əˈwer/", "adj.", "意识到的", "Are you aware of the risks involved?", "你意识到其中涉及的风险了吗？", "B2"),
  w("challenge", "/ˈtʃælɪndʒ/", "n./v.", "挑战", "Learning a new language is a big challenge.", "学习一门新语言是一个巨大的挑战。", "B2"),
  w("concentrate", "/ˈkɑːnsntreɪt/", "v.", "集中（注意力）", "It's hard to concentrate in a noisy room.", "在嘈杂的房间里很难集中注意力。", "B2"),
  w("conflict", "/ˈkɑːnflɪkt/", "n.", "冲突；矛盾", "The conflict between the two groups lasted for years.", "两个群体之间的冲突持续了多年。", "B2"),
  w("determine", "/dɪˈtɜːrmɪn/", "v.", "决定；查明", "The results will determine our next step.", "结果将决定我们的下一步。", "B2"),
  w("efficient", "/ɪˈfɪʃənt/", "adj.", "高效的", "This is a more efficient way to study vocabulary.", "这是一种更高效的学习词汇的方法。", "B2"),
  w("evidence", "/ˈevɪdəns/", "n.", "证据", "There is no evidence to support this claim.", "没有证据支持这一说法。", "B2"),
  w("essential", "/ɪˈsenʃl/", "adj.", "必不可少的", "Sleep is essential for memory and learning.", "睡眠对记忆和学习至关重要。", "B2"),
  w("evaluate", "/ɪˈvæljueɪt/", "v.", "评估；评价", "Teachers evaluate students' progress every term.", "老师每学期都会评估学生的进步。", "B2"),
  w("flexible", "/ˈfleksəbl/", "adj.", "灵活的", "Our class schedule is quite flexible.", "我们的课程安排相当灵活。", "B2"),
  w("generate", "/ˈdʒenəreɪt/", "v.", "产生；生成", "The solar panel generates clean electricity.", "太阳能电池板产生清洁电力。", "B2"),
  w("hesitate", "/ˈhezɪteɪt/", "v.", "犹豫", "Don't hesitate to ask questions in class.", "在课堂上不要犹豫，尽管提问。", "B2"),
  w("identical", "/aɪˈdentɪkl/", "adj.", "完全相同的", "The two copies of the report are identical.", "报告的两个副本完全相同。", "B2"),
  w("interpret", "/ɪnˈtɜːrprt/", "v.", "解释；理解", "How should we interpret this result?", "我们该如何理解这个结果？", "B2"),
  w("maintain", "/meɪnˈteɪn/", "v.", "维持；保养", "It's important to maintain a healthy diet.", "保持健康的饮食很重要。", "B2"),
  w("negotiate", "/nɪˈɡoʊʃieɪt/", "v.", "谈判；协商", "They negotiated a better price with the supplier.", "他们与供应商谈到了更好的价格。", "B2"),
  w("particular", "/pərˈtɪkjələr/", "adj.", "特定的；特别的", "Is there a particular reason for the delay?", "延误有特别的原因吗？", "B2"),
  w("significant", "/sɪɡˈnɪfɪkənt/", "adj.", "重要的；显著的", "The company saw significant growth last year.", "公司去年实现了显著增长。", "B2"),

  // ───────────────────────── C1 ─────────────────────────
  w("ambiguous", "/æmˈbɪɡjuəs/", "adj.", "模棱两可的", "His answer was deliberately ambiguous.", "他的回答故意含糊其辞。", "C1"),
  w("comprehensive", "/ˌkɑːmprɪˈhensɪv/", "adj.", "全面的；综合的", "The report gives a comprehensive overview of the market.", "这份报告对市场进行了全面的概述。", "C1"),
  w("deliberate", "/dɪˈlɪbərət/", "adj.", "故意的；蓄意的", "The damage to the equipment was deliberate.", "对设备的损坏是蓄意为之的。", "C1"),
  w("emphasize", "/ˈemfəsaɪz/", "v.", "强调", "The teacher emphasized the key points of the lesson.", "老师强调了这节课的重点。", "C1"),
  w("feasible", "/ˈfiːzəbl/", "adj.", "可行的", "The project is technically feasible, but costly.", "这个项目在技术上是可行的，但成本很高。", "C1"),
  w("hypothesis", "/haɪˈpɑːθəsɪs/", "n.", "假设", "The experiment was designed to test the hypothesis.", "这个实验是为了检验该假设而设计的。", "C1"),
  w("inevitable", "/ɪnˈevɪtəbl/", "adj.", "不可避免的", "Change is inevitable in any growing company.", "在快速发展的公司里，变化是不可避免的。", "C1"),
  w("meticulous", "/məˈtɪkjələs/", "adj.", "一丝不苟的", "She is meticulous about every detail of the plan.", "她对计划的每一个细节都一丝不苟。", "C1"),
  w("paradox", "/ˈpærədɑːks/", "n.", "悖论", "It is a paradox that more choices can make us less happy.", "选择越多反而越不快乐，这是个悖论。", "C1"),
  w("perspective", "/pərˈspektɪv/", "n.", "视角；观点", "Try to see the problem from a different perspective.", "试着从不同的角度看这个问题。", "C1"),
  w("phenomenon", "/fəˈnɑːmɪnən/", "n.", "现象", "Sleeping is a natural phenomenon for all mammals.", "睡眠是所有哺乳动物的一种自然现象。", "C1"),
  w("profound", "/prəˈfaʊnd/", "adj.", "深刻的；深远的", "The book had a profound effect on my thinking.", "这本书对我的思维方式产生了深远的影响。", "C1"),
  w("resilience", "/rɪˈzɪliəns/", "n.", "韧性；恢复力", "Resilience helps us recover from setbacks.", "韧性帮助我们走出挫折。", "C1"),
  w("scrutinize", "/ˈskruːtənaɪz/", "v.", "仔细审查", "Investors scrutinized the company's accounts carefully.", "投资者仔细审查了公司的账目。", "C1"),
  w("tentative", "/ˈtentətv/", "adj.", "试探性的；不确定的", "We reached a tentative agreement on the budget.", "我们在预算上达成了初步协议。", "C1"),
  w("ubiquitous", "/juːˈbkwtəs/", "adj.", "无处不在的", "Smartphones have become truly ubiquitous.", "智能手机已经真正无处不在。", "C1"),
  w("alleviate", "/əˈliːvieɪt/", "v.", "缓解；减轻", "This medicine can alleviate the pain.", "这种药可以缓解疼痛。", "C1"),
  w("controversy", "/ˈkɑːntrəvɜːrsi/", "n.", "争议；争论", "The new policy caused a lot of controversy.", "新政策引发了许多争议。", "C1"),
  w("deteriorate", "/dɪˈtɪriəreɪt/", "v.", "恶化；变坏", "His health began to deteriorate last winter.", "他的健康从去年冬天开始恶化。", "C1"),
  w("articulate", "/ɑːrˈtɪkjuleɪt/", "v./adj.", "清楚地表达；善于表达的", "She articulated her concerns clearly in the meeting.", "她在会上清楚地表达了自己的担忧。", "C1"),
]
